In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('./data.txt')

In [5]:
data

name  hrs  marks
0    A    1     10
1    B    2     20
2    D    4     40

In [6]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()

In [12]:
X = data['hrs'].values.reshape(-1,1)
y = data['marks']

In [13]:
model.fit(X,y)

LinearRegression()

In [14]:
model.predict([[3]])

array([30.])

In [16]:
model.coef_

array([10.])

# Predict Product Price

In [55]:
product_data = pd.read_csv('./products.txt')

In [56]:
X = product_data['price'].values.reshape(-1,1)
y = product_data['freq']

In [57]:
p_model = LinearRegression()

In [58]:
p_model.fit(X,y)

LinearRegression()

In [59]:
p_model.predict([[9]])

array([84.48910412])

In [60]:
p_model.coef_

array([11.54600484])

In [64]:
p_model.predict([[3]])

array([15.21307506])

## Linear Regression

In [39]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
import numpy as np

In [11]:
dataset = pd.read_csv("./data.txt")
x = dataset["experience"]
X = x.values.reshape(-1,1)
y = dataset["salary"]

### Model Training

In [15]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [17]:
model.predict([[5]])

array([97023.80952381])

### Model Testing

In [27]:
# Coeficient (relation)
weight = model.coef_
print(weight)

[26047.61904762]


In [24]:
# Bias
model.intercept_

-33214.28571428571

In [40]:
y_predict = model.predict(X)
print(y_predict)
print(np.array(y))

[ -7166.66666667  18880.95238095  44928.57142857  70976.19047619
  97023.80952381 123071.42857143 149119.04761905 175166.66666667]
[ 15000  25000  35000  37000 100000 120000 140000 200000]


In [32]:
# Error or difference between prediction and original value
er = mean_absolute_error(y, y_predict)
print(er)

14023.80952380952


In [42]:
# Testing
accuracy = accuracy_score(y,y_predict)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets