In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('./data.txt')

In [5]:
data

name  hrs  marks
0    A    1     10
1    B    2     20
2    D    4     40

In [6]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()

In [12]:
X = data['hrs'].values.reshape(-1,1)
y = data['marks']

In [13]:
model.fit(X,y)

LinearRegression()

In [14]:
model.predict([[3]])

array([30.])

In [16]:
model.coef_

array([10.])

# Predict Product Price

In [55]:
product_data = pd.read_csv('./products.txt')

In [56]:
X = product_data['price'].values.reshape(-1,1)
y = product_data['freq']

In [57]:
p_model = LinearRegression()

In [58]:
p_model.fit(X,y)

LinearRegression()

In [59]:
p_model.predict([[9]])

array([84.48910412])

In [60]:
p_model.coef_

array([11.54600484])

In [64]:
p_model.predict([[3]])

array([15.21307506])

In [65]:
class visitorform:
    Name = None 
    City = None
    phone = None

In [66]:
jack=visitorform()

In [67]:
jack

In [68]:
shubh=visitorform()

In [69]:
shubh

In [71]:
shubh.__dict__

{}

In [72]:
shubh.Name='satya'

In [73]:
shubh.City='vns'

In [74]:
shubh.phone='70848'

In [75]:
shubh.__dict__

{'Name': 'satya', 'City': 'vns', 'phone': '70848'}

In [77]:
satya=visitorform()

In [78]:
satya.Name= 'bhabhi'

In [79]:
satya.City='ghar'

In [81]:
satya.phone='bhabhi ka no, nhi pata'

In [82]:
satya.__dict__

{'Name': 'bhabhi', 'City': 'ghar', 'phone': 'bhabhi ka no, nhi pata'}